'use server';
/**
 * @fileOverview A Genkit flow for cleaning audio transcripts.
 *
 * - cleanAudio - A function that handles the audio cleaning process, including detecting and removing filler words and integrating silence/low energy sections.
 * - AiAudioCleanerInput - The input type for the cleanAudio function.
 * - AiAudioCleanerOutput - The return type for the cleanAudio function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

// Note: This flow focuses on the LLM part of audio cleaning. The actual Whisper transcription and
// initial detection of silences and low energy sections would typically occur as preceding steps
// in an AWS Step Functions pipeline or via dedicated tools/services before invoking this LLM flow.

const AiAudioCleanerInputSchema = z.object({
  transcript: z.string().describe('The full transcript of the audio generated by Whisper or another transcription service.'),
  audioDataUri: z
    .string()
    .describe(
      "The original audio file as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'. This is provided for context but not directly processed by the LLM in this flow."
    ),
  detectedSilences: z
    .array(z.object({ start: z.number(), end: z.number() }))
    .optional()
    .describe('Pre-detected silence segments (start and end time in seconds) from audio analysis. The LLM will integrate this into its output.'),
  detectedLowEnergySections: z
    .array(z.object({ start: z.number(), end: z.number() }))
    .optional()
    .describe('Pre-detected low energy sections (start and end time in seconds) from audio analysis. The LLM will integrate this into its output.'),
});
export type AiAudioCleanerInput = z.infer<typeof AiAudioCleanerInputSchema>;

const AiAudioCleanerOutputSchema = z.object({
  cleanedTranscript: z.string().describe('The transcript with filler words and, potentially, suggested silence sections removed to create a more polished version.'),
  removedSilences: z.array(z.object({ start: z.number(), end: z.number() })).describe('List of silence segments (start and end time in seconds) identified from the audio, as provided in input or inferred.'),
  removedFillers: z
    .array(z.object({ text: z.string(), startIndex: z.number(), endIndex: z.number() }))
    .describe('List of filler words (e.g., "um", "uh", "like", "you know") identified and removed from the original transcript, along with their approximate start and end character indices.'),
  lowEnergySections: z.array(z.object({ start: z.number(), end: z.number() })).describe('List of low energy sections (start and end time in seconds) identified from the audio, as provided in input or inferred.'),
});
export type AiAudioCleanerOutput = z.infer<typeof AiAudioCleanerOutputSchema>;

export async function cleanAudio(input: AiAudioCleanerInput): Promise<AiAudioCleanerOutput> {
  return aiAudioCleanerFlow(input);
}

const aiAudioCleanerPrompt = ai.definePrompt({
  name: 'aiAudioCleanerPrompt',
  input: { schema: AiAudioCleanerInputSchema },
  output: { schema: AiAudioCleanerOutputSchema },
  prompt: (input) => `You are an expert podcast audio editor and transcriber. Your task is to review a given audio transcript, identify and remove common filler words, and consolidate information about silence and low energy sections.

Instructions:
1. Analyze the provided 'transcript' and identify common filler words such as "um", "uh", "like", "you know", "so", "right", etc. When identifying filler words, also determine their approximate start and end character indices within the original transcript.
2. Create a 'cleanedTranscript' by removing these identified filler words. Ensure the cleaned transcript flows naturally and professionally.
3. Populate the 'removedFillers' array with the identified filler words, their text, and their original 'startIndex' and 'endIndex' in the raw transcript.
4. Re-output the 'detectedSilences' and 'detectedLowEnergySections' arrays into the 'removedSilences' and 'lowEnergySections' fields in the output JSON. If these are not provided in the input, assume empty arrays for them.

Original Transcript:
${input.transcript}

Pre-detected Silences (if any):
${JSON.stringify(input.detectedSilences)}

Pre-detected Low Energy Sections (if any):
${JSON.stringify(input.detectedLowEnergySections)}`,
});

const aiAudioCleanerFlow = ai.defineFlow(
  {
    name: 'aiAudioCleanerFlow',
    inputSchema: AiAudioCleanerInputSchema,
    outputSchema: AiAudioCleanerOutputSchema,
  },
  async (input) => {
    const {output} = await aiAudioCleanerPrompt(input);
    // Ensure output fields for silences and low energy sections are populated,
    // even if they were optional in input but required in output.
    return {
      ...output!,
      removedSilences: output?.removedSilences || input.detectedSilences || [],
      lowEnergySections: output?.lowEnergySections || input.detectedLowEnergySections || [],
    };
  }
);
