'use client';

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AiLaunchStrategyOutput } from "@/ai/flows/ai-launch-strategy-flow";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Bot, Calendar, ListChecks, Mic, Lightbulb, Users, FileText, Clock } from "lucide-react";

export default function StrategyPage() {
    const router = useRouter();
    const [strategy, setStrategy] = useState<AiLaunchStrategyOutput | null>(null);

    useEffect(() => {
        const storedStrategy = localStorage.getItem("launchStrategy");
        if (storedStrategy) {
            setStrategy(JSON.parse(storedStrategy));
            // Optional: clear it after reading so it's not stale
            // localStorage.removeItem("launchStrategy");
        } else {
            // If no strategy is found, maybe redirect back to onboarding
            router.push('/dashboard/onboarding');
        }
    }, [router]);

    if (!strategy) {
        return (
            <div className="flex items-center justify-center h-96">
                <Bot className="w-12 h-12 animate-spin text-primary" />
                <p className="ml-4 text-lg">Loading your AI Strategy...</p>
            </div>
        );
    }

    return (
        <div className="space-y-8">
            <Card className="glass-vivid border-none relative overflow-hidden">
                <div className="absolute inset-0 bg-gradient-to-r from-primary/10 via-transparent to-accent/10 pointer-events-none" />
                <CardHeader className="relative z-10 py-8">
                    <CardTitle className="font-headline text-4xl font-black tracking-tight flex items-center gap-4">
                        <div className="bg-primary/20 p-3 rounded-2xl">
                            <Lightbulb className="text-primary h-8 w-8" />
                        </div>
                        Your AI Launch Strategy
                    </CardTitle>
                    <CardDescription className="text-lg text-muted-foreground ml-16">
                        Here is your personalized, high-growth plan generated by Gemini AI.
                    </CardDescription>
                </CardHeader>
            </Card>

            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                <Card className="glass-vivid border-none overflow-hidden">
                    <CardHeader className="pb-4">
                        <CardTitle className="flex items-center gap-3 text-xl font-bold"><Mic className="text-primary" /> Podcast Format</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <div className="bg-background/20 p-6 rounded-[2rem] border border-white/10">
                            <p className="text-lg font-medium text-foreground">{strategy.podcastFormat}</p>
                        </div>
                    </CardContent>
                </Card>
                <Card className="lg:col-span-2 glass-vivid border-none">
                    <CardHeader className="pb-6">
                        <CardTitle className="flex items-center gap-3 text-xl font-bold"><ListChecks className="text-primary" /> Episode Structure</CardTitle>
                    </CardHeader>
                    <CardContent className="grid md:grid-cols-3 gap-6">
                        <div className="bg-background/20 p-6 rounded-[2rem] border border-white/10 space-y-3">
                            <h4 className="font-black text-xs uppercase tracking-widest text-primary/80">Intro</h4>
                            <p className="text-sm leading-relaxed text-muted-foreground">{strategy.episodeStructure.intro}</p>
                        </div>
                        <div className="bg-background/20 p-6 rounded-[2rem] border border-white/10 space-y-3">
                            <h4 className="font-black text-xs uppercase tracking-widest text-primary/80">Segments</h4>
                            <ul className="space-y-2">
                                {strategy.episodeStructure.segments.map((segment, i) => (
                                    <li key={i} className="text-sm flex gap-2 text-muted-foreground italic">
                                        <span className="text-primary">•</span> {segment}
                                    </li>
                                ))}
                            </ul>
                        </div>
                        <div className="bg-background/20 p-6 rounded-[2rem] border border-white/10 space-y-3">
                            <h4 className="font-black text-xs uppercase tracking-widest text-primary/80">Outro</h4>
                            <p className="text-sm leading-relaxed text-muted-foreground">{strategy.episodeStructure.outro}</p>
                        </div>
                    </CardContent>
                </Card>
            </div>

            <Card>
                <CardHeader>
                    <CardTitle className="flex items-center gap-2"><Clock /> Posting Strategy</CardTitle>
                </CardHeader>
                <CardContent className="space-y-2">
                    <h4 className="font-semibold">{strategy.postingStrategy.recommendation}</h4>
                    <p className="text-muted-foreground">{strategy.postingStrategy.reasoning}</p>
                </CardContent>
            </Card>

            <Card className="glass-vivid border-none">
                <CardHeader>
                    <CardTitle className="flex items-center gap-4 text-2xl font-black"><Users className="text-primary h-7 w-7" /> Guest Recommendations</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                    {strategy.guestRecommendations.map((guest, i) => (
                        <div key={i} className="bg-background/40 hover:bg-background/60 transition-colors p-4 px-8 rounded-full border border-white/10 text-foreground font-medium flex items-center gap-3">
                            <span className="h-2 w-2 rounded-full bg-primary" />
                            {guest}
                        </div>
                    ))}
                </CardContent>
            </Card>

            <Card className="glass-vivid border-none">
                <CardHeader>
                    <CardTitle className="flex items-center gap-4 text-2xl font-black"><FileText className="text-primary h-7 w-7" /> Episode Themes</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                    {strategy.episodeThemes.map((theme, i) => (
                        <div key={i} className="bg-background/40 hover:bg-background/60 transition-colors p-4 px-8 rounded-full border border-white/10 text-foreground font-medium flex items-center justify-between group">
                            <span className="flex-1">{theme}</span>
                            <div className="h-1 w-12 rounded-full bg-primary/20 group-hover:bg-primary transition-colors" />
                        </div>
                    ))}
                </CardContent>
            </Card>

            <Card className="glass-vivid border-none">
                <CardHeader>
                    <CardTitle className="flex items-center gap-4 text-3xl font-black"><Calendar className="text-primary h-8 w-8" /> 30-Day Content Plan</CardTitle>
                </CardHeader>
                <CardContent>
                    <div className="grid gap-6">
                        {strategy.contentPlan.map((item, i) => (
                            <div key={i} className="p-6 rounded-[2.5rem] bg-background/20 border border-white/10 flex items-center gap-8 group hover:border-primary/30 transition-all">
                                <div className="flex flex-col items-center justify-center bg-background/40 h-24 w-24 rounded-[2rem] border border-white/10 shrink-0">
                                    <span className="font-black text-primary text-sm uppercase tracking-tighter">Day</span>
                                    <span className="font-headline text-4xl font-black text-foreground">{item.day}</span>
                                </div>
                                <div className="space-y-3 flex-1">
                                    <p className="text-xl font-bold text-foreground leading-tight">{item.idea}</p>
                                    <Badge className="bg-purple-600/80 hover:bg-purple-600 text-white rounded-lg px-4 py-1 border-none font-black text-xs">
                                        {item.platform.toUpperCase()}
                                    </Badge>
                                </div>
                            </div>
                        ))}
                    </div>
                </CardContent>
            </Card>

            <Card className="glass-vivid border-none">
                <CardHeader>
                    <CardTitle className="flex items-center gap-4 text-2xl font-black"><Clock className="text-primary h-7 w-7" /> Posting Strategy</CardTitle>
                </CardHeader>
                <CardContent className="space-y-6">
                    <div className="bg-background/40 p-8 rounded-[2rem] border-l-4 border-l-primary space-y-4">
                        <h4 className="text-2xl font-black text-foreground leading-tight italic">
                            "{strategy.postingStrategy.recommendation}"
                        </h4>
                        <p className="text-lg text-muted-foreground leading-relaxed">
                            {strategy.postingStrategy.reasoning}
                        </p>
                    </div>
                </CardContent>
            </Card>

            <div className="text-center py-12">
                <Button size="lg" onClick={() => router.push('/dashboard')} className="h-16 px-12 text-xl font-black rounded-2xl bg-primary text-primary-foreground hover:bg-primary/90 shadow-2xl transition-all hover:translate-y-[-2px]">
                    Go to Dashboard
                </Button>
            </div>

        </div>
    );
}
