'use client';

import React, { createContext, useState, ReactNode } from 'react';
import { Episode, NewEpisodePayload } from '@/lib/types';
import { episodes as initialEpisodes } from '@/lib/mock-data';
import { useToast } from '@/hooks/use-toast';
import { cleanAudio } from '@/ai/flows/ai-audio-cleaner-flow';
import { aiEngagementScorer } from '@/ai/flows/ai-engagement-scorer-flow';
import { generateSocialMediaContent } from '@/ai/flows/ai-social-media-generator-flow';

// A mock transcript for simulation purposes
const mockTranscript = `
Welcome to PodVision AI, the podcast that explores the cutting edge of artificial intelligence and its impact on our world. I'm your host, Alex.
In today's episode, we're diving deep into a fascinating and, uh, slightly controversial topic: the emergence of creative AI. Can a machine truly be creative? Or is it just a sophisticated mimic? We have two amazing guests with us today. Dr. Lena Petrova, a leading researcher in generative models, and Marcus Vance, a digital artist who has been, you know, collaborating with AI for his latest collection. Welcome to you both.
Lena, let's start with you. When we talk about AI creativity, what do we actually mean? Is it just pattern recognition on a massive scale?
Well, Alex, that's the billion-dollar question, isn't it? On one hand, yes, a large language model is trained on vast datasets of existing human creativity. So, in a way, it is remixing what it has learned. But... and this is the important part... the way it combines, transforms, and generates something novel can be indistinguishable from human creativity. It's like, uh, a musician learning all the scales and chords in the world and then composing a new symphony. Are they not creative because they used existing notes? I think it's a similar principle. The scale is just... astronomical.
That's a great analogy. Marcus, you work hands-on with these tools. Does it feel like a collaboration, or are you just giving orders to a very advanced program?
It's absolutely a collaboration. It's like having a brainstorming partner who has seen every piece of art ever created. I can give it a vague concept, like 'a lonely astronaut discovering a neon jungle on Mars,' and it will generate a dozen visual starting points. Some are junk, to be honest. But then, one or two will have a spark, a weird composition or color palette that I would have never thought of. That spark is what I then take and build upon. It's a conversation. It, like, pushes me to be more creative. The AI suggests, I curate and refine. It's a dance.
So, there’s a real synergy. That’s fascinating. But what about the, um, ethical implications? If an AI creates a masterpiece, who gets the credit? The AI? The programmer? The artist who provided the prompt?
That's where things get messy, and the legal frameworks are lagging far behind the technology. Right now, in most places, you can't copyright work that's solely generated by AI. But the term 'solely' is the key. By being part of the process, like Marcus is, he is adding the essential human element of authorship. My personal view is that we need a new category of intellectual property. It’s not human, it’s not machine, it’s a hybrid. It's a very, very complex area. We'll probably see major court cases around this in the next, you know, five years.
A truly new frontier. This has been an incredible discussion. Thank you both for your insights. It seems the future of creativity is not human versus machine, but human with machine. Join us next week as we explore AI in medicine.
`;

type EpisodesContextType = {
  episodes: Episode[];
  addEpisode: (payload: NewEpisodePayload) => void;
  updateEpisode: (episodeId: string, updates: Partial<Episode>) => void;
  isProcessing: boolean;
};

export const EpisodesContext = createContext<EpisodesContextType>({
  episodes: [],
  addEpisode: () => {},
  updateEpisode: () => {},
  isProcessing: false,
});

export const EpisodesProvider = ({ children }: { children: ReactNode }) => {
  const [episodes, setEpisodes] = useState<Episode[]>(initialEpisodes);
  const [isProcessing, setIsProcessing] = useState(false);
  const { toast } = useToast();

  const updateEpisode = (episodeId: string, updates: Partial<Episode>) => {
    setEpisodes((prevEpisodes) =>
      prevEpisodes.map((ep) =>
        ep.id === episodeId ? { ...ep, ...updates } : ep
      )
    );
  };

  const addEpisode = async (payload: NewEpisodePayload) => {
    if (isProcessing) {
        toast({
            title: "Processing in Progress",
            description: "An episode is already being processed. Please wait.",
            variant: "destructive"
        });
        return;
    }
    setIsProcessing(true);

    const newEpisode: Episode = {
      id: `ep${episodes.length + 1}`,
      title: payload.title,
      uploadDate: new Date().toISOString().split('T')[0],
      duration: '00:00', // Placeholder
      status: 'processing',
      imageUrl: 'https://picsum.photos/seed/' + Math.random() + '/400/400',
      imageHint: 'abstract art'
    };

    setEpisodes((prev) => [newEpisode, ...prev]);

    try {
      // 1. Clean Audio (Simulated)
      const cleanedResult = await cleanAudio({
        transcript: mockTranscript,
        audioDataUri: '',
      });
      updateEpisode(newEpisode.id, { processingResult: cleanedResult });

      // 2. Score Engagement
      const scoreResult = await aiEngagementScorer({
        cleanedTranscript: cleanedResult.cleanedTranscript,
        removedSilences: cleanedResult.removedSilences,
        removedFillers: cleanedResult.removedFillers,
        lowEnergySections: cleanedResult.lowEnergySections,
      });
      updateEpisode(newEpisode.id, { podScore: scoreResult });
      
      // 3. Generate Social Content
      const socialContentResult = await generateSocialMediaContent({
        podcastTitle: "PodVision AI Podcast",
        episodeTitle: newEpisode.title,
        podcastNiche: "AI and Technology",
        targetAudience: "Tech enthusiasts and creators",
        highMoments: scoreResult.highMoments,
      });

      // 4. Final Update
      updateEpisode(newEpisode.id, { 
        status: 'completed',
        contentAssets: socialContentResult 
      });

      toast({
        title: "Processing Complete!",
        description: `"${newEpisode.title}" has been successfully analyzed.`,
      });

    } catch (error) {
      console.error("AI processing pipeline failed:", error);
      updateEpisode(newEpisode.id, { status: 'failed' });
      toast({
        title: "Processing Failed",
        description: `There was an error analyzing "${newEpisode.title}".`,
        variant: "destructive",
      });
    } finally {
        setIsProcessing(false);
    }
  };

  return (
    <EpisodesContext.Provider value={{ episodes, addEpisode, updateEpisode, isProcessing }}>
      {children}
    </EpisodesContext.Provider>
  );
};
